# Generated by Django 6.0.4 on 2026-05-03 18:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField(help_text='Overall mood today (1 = very bad, 10 = excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_hours', models.FloatField(help_text='Hours of sleep last night', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('work_hours', models.FloatField(help_text='Hours spent on work or study today', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('self_stress_level', models.IntegerField(help_text='Self-reported stress level (1 = calm, 10 = extreme)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('anxiety_level', models.IntegerField(default=5, help_text='How anxious did you feel today? (1 = not at all, 10 = severely)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_level', models.IntegerField(default=5, help_text='Overall energy level today (1 = exhausted, 10 = very energetic)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('social_interaction', models.CharField(choices=[('Low', 'Low — I mostly stayed alone'), ('Medium', 'Medium — Some interaction'), ('High', 'High — Very social today')], default='Medium', help_text='Level of social interaction today', max_length=10)),
                ('appetite_level', models.CharField(choices=[('Low', 'Low — I barely ate'), ('Normal', 'Normal — Ate as usual'), ('High', 'High — Overate / stress eating')], default='Normal', help_text='Appetite level today', max_length=10)),
                ('concentration_level', models.IntegerField(default=5, help_text='Ability to concentrate today (1 = very poor, 10 = excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('motivation_level', models.IntegerField(default=5, help_text='Motivation to do tasks today (1 = none, 10 = highly motivated)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('screen_time', models.FloatField(default=0.0, help_text='Total recreational screen time in hours (phone, TV, social media)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('physical_activity', models.BooleanField(default=False, help_text='Did you do any physical exercise or activity today?')),
                ('feeling_hopeless', models.BooleanField(default=False, help_text='Did you feel hopeless or worthless today?')),
                ('loss_of_interest', models.BooleanField(default=False, help_text='Did you lose interest in activities you usually enjoy?')),
                ('feeling_tired', models.BooleanField(default=False, help_text='Did you feel tired or fatigued for most of the day?')),
                ('trouble_sleeping', models.BooleanField(default=False, help_text='Did you have trouble falling or staying asleep?')),
                ('notes', models.TextField(blank=True, help_text='Any additional thoughts about today')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date'],
                'unique_together': {('user', 'entry_date')},
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress_category', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('burnout_risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('depression_score', models.IntegerField(default=0, help_text='0–4 depression indicator count')),
                ('depression_risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('recommendations', models.TextField(blank=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='tracker.moodentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
